### ISSUE TITLE
how to use this lib?

### ISSUE THREAD

**Issue by luclissi** [mongoose-os-libs/sntp#1]
Hello I find to lib about the sntp for do this function ```void mgos_sntp_add_time_change_cb(mgos_sntp_time_change_cb cb, void *arg);```
How to use this in mjs? Is to ```ffi("void mgos_sntp_add_time_change_cb(mgos_sntp_time_change_cb cb, void *arg)")```?

**Comment by luclissi** [comment]
I did this to solved, but the delta is not returned
```
let timerSNTP = ffi("void mgos_sntp_add_time_change_cb(void(*)(userdata), userdata)");
timerSNTP(function(args,delta) {
      print("SNTP CALLBACK!");
}, null);
```

**Comment by dimonomid** [comment]
@lucca-ecclissi , hold on, this repo is empty at the moment, hopefully sntp functionality will be moved here soon, but this will also cause the API to change: the [mgos_event](https://mongoose-os.com/docs/api/mgos_event.h.html) API will be used in order to subscribe to time change events.

**Comment by luclissi** [comment]
@dimonomid Thank you for your attention and sorry for the rush. 
I will try to implement this Event API and be watching the repository.
